"""Initial schema.

Creates the full Study League data model: identity, subjects and the study-session event
log, planning, social scaffolding, and the league tables.

Two things autogenerate could not emit for SQLite and that are added by hand at the end of
`upgrade()`: the case-insensitive uniqueness indexes on email/username/subject name. They
are expression indexes, which SQLAlchemy cannot reflect on SQLite, so autogenerate skips
them (see ADR-0003).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("actor_type", sa.String(length=8), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "before",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_created", ["created_at"], unique=False)
        batch_op.create_index("ix_audit_entity", ["entity_type", "entity_id"], unique=False)

    op.create_table(
        "league_categories",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "league_seasons",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "scoring_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("promotion_rate", sa.Float(), nullable=False),
        sa.Column("relegation_rate", sa.Float(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("ends_on > starts_on", name="ck_season_dates_ordered"),
        sa.CheckConstraint(
            "promotion_rate + relegation_rate <= 1", name="ck_season_rates_leave_middle"
        ),
        sa.CheckConstraint(
            "promotion_rate >= 0 AND promotion_rate <= 1", name="ck_season_promotion_rate"
        ),
        sa.CheckConstraint(
            "relegation_rate >= 0 AND relegation_rate <= 1", name="ck_season_relegation_rate"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("auth_provider", sa.String(length=16), nullable=False),
        sa.Column("provider_subject", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "(auth_provider = 'email' AND password_hash IS NOT NULL) OR (auth_provider <> 'email' AND provider_subject IS NOT NULL)",
            name="ck_users_credential_present",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "uq_users_provider_subject",
            ["auth_provider", "provider_subject"],
            unique=True,
            sqlite_where=sa.text("provider_subject IS NOT NULL"),
            postgresql_where=sa.text("provider_subject IS NOT NULL"),
        )

    op.create_table(
        "daily_plans",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column("reflection", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "plan_date", name="uq_daily_plans_user_date"),
    )
    with op.batch_alter_table("daily_plans", schema=None) as batch_op:
        batch_op.create_index("ix_daily_plans_user_date", ["user_id", "plan_date"], unique=False)

    op.create_table(
        "devices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_hash", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("app_version", sa.String(length=32), nullable=True),
        sa.Column("push_token", sa.String(length=255), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_hash", name="uq_devices_user_hash"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "friendships",
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("requester_id <> addressee_id", name="ck_friendship_not_self"),
        sa.ForeignKeyConstraint(["addressee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requester_id", "addressee_id", name="uq_friendship_pair"),
    )
    with op.batch_alter_table("friendships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_friendships_addressee_id"), ["addressee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_friendships_requester_id"), ["requester_id"], unique=False
        )

    op.create_table(
        "idempotency_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "response_body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            "uq_idempotency_user_key_endpoint", ["user_id", "key", "endpoint"], unique=True
        )

    op.create_table(
        "league_divisions",
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("tier >= 0", name="ck_division_tier_non_negative"),
        sa.ForeignKeyConstraint(["season_id"], ["league_seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "tier", name="uq_division_season_tier"),
    )
    op.create_table(
        "league_missions",
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metric", sa.String(length=48), nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("reward_points", sa.Integer(), nullable=False),
        sa.Column("week_index", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("reward_points >= 0", name="ck_mission_reward_non_negative"),
        sa.CheckConstraint("target > 0", name="ck_mission_target_positive"),
        sa.ForeignKeyConstraint(["season_id"], ["league_seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "slug", name="uq_mission_season_slug"),
    )
    with op.batch_alter_table("league_missions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_league_missions_season_id"), ["season_id"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_user_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "reports",
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=16), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_reporter_id"), ["reporter_id"], unique=False)
        batch_op.create_index("ix_reports_subject", ["subject_type", "subject_id"], unique=False)

    op.create_table(
        "study_goals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("target_weekly_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "subject_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "milestones",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "target_weekly_minutes >= 0", name="ck_goal_weekly_minutes_non_negative"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("study_goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_study_goals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "study_groups",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rules", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=8), nullable=False),
        sa.Column("invite_code", sa.String(length=12), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("max_members BETWEEN 2 AND 500", name="ck_group_capacity"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_code"),
    )
    op.create_table(
        "subjects",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("color_hex", sa.String(length=7), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("length(color_hex) = 7", name="ck_subjects_color_format"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subjects_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("study_category", sa.String(length=64), nullable=False),
        sa.Column("bio", sa.String(length=280), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("daily_goal_minutes", sa.Integer(), nullable=False),
        sa.Column("weekly_goal_minutes", sa.Integer(), nullable=False),
        sa.Column("scheduled_study_days", sa.Integer(), nullable=False),
        sa.Column("pomodoro_focus_minutes", sa.Integer(), nullable=False),
        sa.Column("pomodoro_break_minutes", sa.Integer(), nullable=False),
        sa.Column("privacy_show_subject", sa.Boolean(), nullable=False),
        sa.Column("privacy_show_presence", sa.Boolean(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("daily_goal_minutes BETWEEN 0 AND 1440", name="ck_daily_goal_range"),
        sa.CheckConstraint(
            "pomodoro_break_minutes BETWEEN 1 AND 60", name="ck_pomodoro_break_range"
        ),
        sa.CheckConstraint(
            "pomodoro_focus_minutes BETWEEN 1 AND 180", name="ck_pomodoro_focus_range"
        ),
        sa.CheckConstraint(
            "scheduled_study_days BETWEEN 0 AND 127", name="ck_scheduled_days_bitmask"
        ),
        sa.CheckConstraint("weekly_goal_minutes BETWEEN 0 AND 10080", name="ck_weekly_goal_range"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "group_invitations",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("inviter_id", sa.Uuid(), nullable=False),
        sa.Column("invitee_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("inviter_id <> invitee_id", name="ck_invitation_not_self"),
        sa.ForeignKeyConstraint(["group_id"], ["study_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invitee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "invitee_id", name="uq_group_invitation_target"),
    )
    with op.batch_alter_table("group_invitations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_invitations_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_group_invitations_invitee_id"), ["invitee_id"], unique=False
        )

    op.create_table(
        "group_memberships",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["group_id"], ["study_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_membership"),
    )
    with op.batch_alter_table("group_memberships", schema=None) as batch_op:
        batch_op.create_index("ix_group_memberships_user", ["user_id"], unique=False)

    op.create_table(
        "league_cohorts",
        sa.Column("division_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("capacity BETWEEN 20 AND 30", name="ck_cohort_capacity_range"),
        sa.ForeignKeyConstraint(["category_id"], ["league_categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["division_id"], ["league_divisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("league_cohorts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_cohorts_division_category", ["division_id", "category_id"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "study_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("focus_mode", sa.String(length=12), nullable=False),
        sa.Column("pomodoro_focus_minutes", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("went_as_planned", sa.Boolean(), nullable=True),
        sa.Column("integrity_status", sa.String(length=12), nullable=False),
        sa.Column(
            "integrity_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("client_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "source <> 'manual' OR (status = 'completed' AND ended_at IS NOT NULL)",
            name="ck_manual_sessions_are_complete",
        ),
        sa.CheckConstraint("duration_seconds >= 0", name="ck_sessions_duration_non_negative"),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at", name="ck_sessions_ended_after_started"
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("study_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_user_started", ["user_id", "started_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_study_sessions_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            "uq_one_running_session_per_user",
            ["user_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('active', 'paused')"),
            postgresql_where=sa.text("status IN ('active', 'paused')"),
        )

    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deferred_to_plan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "status <> 'done' OR completed_at IS NOT NULL", name="ck_tasks_done_has_timestamp"
        ),
        sa.CheckConstraint("estimated_minutes BETWEEN 0 AND 1440", name="ck_tasks_estimate_range"),
        sa.ForeignKeyConstraint(["deferred_to_plan_id"], ["daily_plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["daily_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_plan_id"), ["plan_id"], unique=False)

    op.create_table(
        "user_mission_progress",
        sa.Column("mission_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("progress >= 0", name="ck_mission_progress_non_negative"),
        sa.ForeignKeyConstraint(["mission_id"], ["league_missions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id", "user_id", name="uq_mission_progress_user"),
    )
    with op.batch_alter_table("user_mission_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_mission_progress_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "league_enrollments",
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("cohort_id", sa.Uuid(), nullable=True),
        sa.Column("placement", sa.String(length=12), nullable=False),
        sa.Column("final_rank", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=12), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["cohort_id"], ["league_cohorts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["season_id"], ["league_seasons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "user_id", name="uq_enrollment_season_user"),
    )
    with op.batch_alter_table("league_enrollments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_league_enrollments_cohort_id"), ["cohort_id"], unique=False
        )

    op.create_table(
        "study_session_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=8), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_event_sequence_positive"),
        sa.ForeignKeyConstraint(["session_id"], ["study_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_session_event_sequence"),
    )
    op.create_table(
        "league_scores",
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("week_index", sa.Integer(), nullable=False),
        sa.Column("points_total", sa.Integer(), nullable=False),
        sa.Column("scoring_version", sa.String(length=16), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("points_total BETWEEN 0 AND 1000", name="ck_score_points_range"),
        sa.CheckConstraint("week_index BETWEEN 0 AND 51", name="ck_score_week_index_range"),
        sa.ForeignKeyConstraint(["enrollment_id"], ["league_enrollments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enrollment_id", "week_index", name="uq_score_enrollment_week"),
    )
    op.create_table(
        "league_score_breakdowns",
        sa.Column("score_id", sa.Uuid(), nullable=False),
        sa.Column("goal_points", sa.Integer(), nullable=False),
        sa.Column("consistency_points", sa.Integer(), nullable=False),
        sa.Column("focus_points", sa.Integer(), nullable=False),
        sa.Column("task_points", sa.Integer(), nullable=False),
        sa.Column("participation_points", sa.Integer(), nullable=False),
        sa.Column(
            "inputs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("excluded_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "exclusion_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["score_id"], ["league_scores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("score_id"),
    )

    # --- Expression indexes (skipped by autogenerate on SQLite) -------------------
    # Case-insensitive uniqueness without depending on PostgreSQL's citext extension.
    op.create_index("uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True)
    op.create_index(
        "uq_user_profiles_username_lower",
        "user_profiles",
        [sa.text("lower(username)")],
        unique=True,
    )
    # Active subject names are unique per user; archived names may repeat, so the index is
    # partial. `is_archived` is stored as 0/1 on SQLite and false/true on PostgreSQL.
    op.create_index(
        "uq_subjects_user_name_active",
        "subjects",
        ["user_id", sa.text("lower(name)")],
        unique=True,
        sqlite_where=sa.text("is_archived = 0"),
        postgresql_where=sa.text("is_archived = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_subjects_user_name_active", table_name="subjects")
    op.drop_index("uq_user_profiles_username_lower", table_name="user_profiles")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("league_score_breakdowns")
    op.drop_table("league_scores")
    op.drop_table("study_session_events")
    with op.batch_alter_table("league_enrollments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_league_enrollments_cohort_id"))

    op.drop_table("league_enrollments")
    with op.batch_alter_table("user_mission_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_mission_progress_user_id"))

    op.drop_table("user_mission_progress")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_plan_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("study_sessions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_one_running_session_per_user",
            sqlite_where=sa.text("status IN ('active', 'paused')"),
            postgresql_where=sa.text("status IN ('active', 'paused')"),
        )
        batch_op.drop_index(batch_op.f("ix_study_sessions_subject_id"))
        batch_op.drop_index("ix_sessions_user_started")

    op.drop_table("study_sessions")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_family_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("league_cohorts", schema=None) as batch_op:
        batch_op.drop_index("ix_cohorts_division_category")

    op.drop_table("league_cohorts")
    with op.batch_alter_table("group_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_group_memberships_user")

    op.drop_table("group_memberships")
    with op.batch_alter_table("group_invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_invitations_invitee_id"))
        batch_op.drop_index(batch_op.f("ix_group_invitations_group_id"))

    op.drop_table("group_invitations")
    op.drop_table("user_settings")
    op.drop_table("user_profiles")
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subjects_user_id"))

    op.drop_table("subjects")
    op.drop_table("study_groups")
    with op.batch_alter_table("study_goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_goals_user_id"))

    op.drop_table("study_goals")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_subject")
        batch_op.drop_index(batch_op.f("ix_reports_reporter_id"))

    op.drop_table("reports")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_created")

    op.drop_table("notifications")
    with op.batch_alter_table("league_missions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_league_missions_season_id"))

    op.drop_table("league_missions")
    op.drop_table("league_divisions")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index("uq_idempotency_user_key_endpoint")

    op.drop_table("idempotency_records")
    with op.batch_alter_table("friendships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_friendships_requester_id"))
        batch_op.drop_index(batch_op.f("ix_friendships_addressee_id"))

    op.drop_table("friendships")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))

    op.drop_table("devices")
    with op.batch_alter_table("daily_plans", schema=None) as batch_op:
        batch_op.drop_index("ix_daily_plans_user_date")

    op.drop_table("daily_plans")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_users_provider_subject",
            sqlite_where=sa.text("provider_subject IS NOT NULL"),
            postgresql_where=sa.text("provider_subject IS NOT NULL"),
        )

    op.drop_table("users")
    op.drop_table("league_seasons")
    op.drop_table("league_categories")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_entity")
        batch_op.drop_index("ix_audit_created")

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
